apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - protocol: 'TCP'
      port: 3500
      targetPort: 3500
  type: ClusterIP
