apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /readyz
spec:
  selector:
    app: backend
  ports:
    - protocol: 'TCP'
      port: 3500
      targetPort: 3500
  type: ClusterIP
